### ISSUE TITLE
Missing attribution for the project description

### ISSUE THREAD

**Issue by chocolateboy** [jedmao/lavadrop#47]
This project appears to have the [same description](https://github.com/jedmao/lavadrop/commit/23fb9a327b27d484d805b044a7e39c672b988622#diff-04c6e90faac2675aa89e2176d2eec7d8) as @angus-c's [Just](https://github.com/angus-c/just), which [inspired it](https://github.com/angus-c/just/issues/126#issuecomment-524424932) (and which is mentioned in the wiki), but I can't see a link back to Just in the README:

## [Just](https://github.com/angus-c/just/blob/65077a6cf685d4237e7856c197ca1fb8e0ca20d4/README.md#just)

> A library of **zero-dependency** npm modules that do just do one thing. A guilt-free alternative to those bulkier utility libraries. Ideal for PWA development or whenever bytes are precious.
>
> **[Jump To API](#the-modules-package)**
>
> We welcome contributions. Please follow our [contribution guidelines](https://github.com/angus-c/just/blob/master/CONTRIBUTING.md).

## [Lavadrop](https://github.com/jedmao/lavadrop/blob/c5fde318563774a59f7cf468a501e7a445acd71d/README.md)

> A library of **zero-dependency** [npm modules](https://www.npmjs.com/org/lavadrop) that do just one thing. A guilt-free alternative to those bulkier utility libraries. Ideal for [PWA](https://developers.google.com/web/progressive-web-apps/) development or whenever bytes are precious.
>
> See the [Documentation Site](https://lavadrop.com/)!
>
> We welcome contributions. Please follow our [contribution guidelines](https://github.com/jedmao/lavadrop/blob/master/.github/CONTRIBUTING.md).

I would suggest either writing a new description or crediting the original project, rather than duplicating the text without attribution.

**Comment by jedmao** [comment]
https://github.com/jedmao/lavadrop/commit/458dc90202fd29252f308713da3079aed5a31b70
